"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Construction des chemins dans le projet, BASE_DIR correspond au dossier racine du projet
BASE_DIR = Path(__file__).resolve().parent.parent


# Paramètres de démarrage rapide - NON adaptés à la production
# Voir https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# ATTENTION : garder la clé secrète confidentielle en production
SECRET_KEY = 'django-insecure-t-e2=b)ffl=%(&pp^1aa(1-oltej(i&#vrem+nedeye#v2z3*t'

# ATTENTION : ne jamais activer le DEBUG en production
DEBUG = True

# Liste des hôtes autorisés à accéder à l'application
ALLOWED_HOSTS = []


# Définition des applications installées dans ce projet Django
INSTALLED_APPS = [
    'django.contrib.admin',           # Interface d'administration
    'django.contrib.auth',            # Gestion des utilisateurs et authentification
    'django.contrib.contenttypes',    # Framework de gestion des types de contenu
    'django.contrib.sessions',        # Gestion des sessions utilisateur
    'django.contrib.messages',        # Gestion des messages flash
    'django.contrib.staticfiles',     # Gestion des fichiers statiques (CSS, JS, images)
    'myapp',                         # Application personnalisée de ce projet
]

# Middleware qui traite les requêtes et réponses HTTP
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # Sécurité (ex : SSL)
    'django.contrib.sessions.middleware.SessionMiddleware',    # Gestion des sessions
    'django.middleware.common.CommonMiddleware',               # Fonctions générales sur les requêtes
    'django.middleware.csrf.CsrfViewMiddleware',               # Protection contre les attaques CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Authentification des utilisateurs
    'django.contrib.messages.middleware.MessageMiddleware',    # Gestion des messages flash
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protection contre le clickjacking
]

# Le module qui gère les URL racines du projet
ROOT_URLCONF = 'myproject.urls'

# Configuration du moteur de templates (HTML) Django
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Backend Django Templates
        'DIRS': [BASE_DIR / 'myapp' / 'templates'],                     # Répertoire des templates personnalisés
        'APP_DIRS': True,                                               # Recherche automatique des templates dans les apps
        'OPTIONS': {
            'context_processors': [                                    # Variables disponibles dans tous les templates
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Application WSGI pour le déploiement
WSGI_APPLICATION = 'myproject.wsgi.application'


# Configuration de la base de données MySQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Utilisation du backend MySQL
        'NAME': 'dbprojet',                    # Nom de la base de données
        'USER': 'root',                        # Nom d'utilisateur MySQL
        'PASSWORD': '',                        # Mot de passe MySQL (vide ici)
        'HOST': '127.0.0.1',                   # Adresse de la base de données (localhost)
        'PORT': '3306',                       # Port MySQL par défaut
    }
}

# Validation des mots de passe (quatre validateurs standards)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Paramètres d’internationalisation

LANGUAGE_CODE = 'en-us'  # Langue anglaise par défaut

TIME_ZONE = 'UTC'        # Fuseau horaire UTC par défaut

USE_I18N = True          # Activation de la traduction internationale

USE_TZ = True            # Activation de la gestion des fuseaux horaires


# Configuration des fichiers statiques (CSS, JS, images)
STATIC_URL = 'static/'  # URL de base pour les fichiers statiques


# Type de clé primaire par défaut pour les modèles
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
